dfRANKREVENUE <- data.frame(eval(parse(text=substring(getURL(URLencode('http://129.152.144.84:5001/rest/native/?query="SELECT COMPANYID, INDUSTRY, REVENUE, rank() OVER (PARTITION BY INDUSTRY order by REVENUE desc) as INDUSTRY_RANK FROM TOPCOMPANIES order by 2,3 desc"'), httpheader=c(DB='jdbc:oracle:thin:@129.152.144.84:1521:ORCL', USER='C##cs329e_nh5797', PASS='orcl_nh5797', MODE='native_mode', MODEL='model', returnFor = 'R', returnDimensions = 'False'), verbose = TRUE), 1, 2^31-1))))

#COMPANYIDData a"select COMPANYIDID, INDUSTRY, REVENUE, rank() over (PARTITION BY INDUSTRY order by REVENUE desc) as INDUSTRY_RANK FROM TOPCOMPANIES order by 2,3 desc"'), httpheader=c(DB='jdbc:oracle:thin:@129.152.144.84:1521:ORCL', USER='C##cs329e_nh5797', PASS='orcl_nh5797', MODE='native_mode', MODEL='model', returnFor = 'R', returnDimensions = 'False'), verbose = TRUE), 1, 2^31-1))))

dfnth <- data.frame(eval(parse(text=substring(getURL(URLencode('http://129.152.144.84:5001/rest/native/?query="SELECT COMPANYID, INDUSTRY, GROWTH, nth_value(GROWTH, 2) OVER (PARTITION BY INDUSTRY) SECOND_GROWTH FROM TOPCOMPANIES order by 2,3 desc"'), httpheader=c(DB='jdbc:oracle:thin:@129.152.144.84:1521:ORCL', USER='C##cs329e_nh5797', PASS='orcl_nh5797', MODE='native_mode', MODEL='model', returnFor = 'R', returnDimensions = 'False'), verbose = TRUE), 1, 2^31-1))))

dfcume_dist <- data.frame(eval(parse(text=substring(getURL(URLencode('http://129.152.144.84:5001/rest/native/?query="SELECT COMPANYID, STATE, REVENUE, cume_dist() OVER (PARTITION BY STATE order by REVENUE) cume_dist from TOPCOMPANIES order by 2,3 desc"'), httpheader=c(DB='jdbc:oracle:thin:@129.152.144.84:1521:ORCL', USER='C##cs329e_nh5797', PASS='orcl_nh5797', MODE='native_mode', MODEL='model', returnFor = 'R', returnDimensions = 'False'), verbose = TRUE), 1, 2^31-1))))

dfMAX <- data.frame(eval(parse(text=substring(getURL(URLencode('http://129.152.144.84:5001/rest/native/?query="SELECT COMPANYID, STATE, GROWTH, last_value(max_GROWTH) OVER (PARTITION BY STATE order by GROWTH) max_GROWTH, last_value(max_GROWTH) OVER (PARTITION BY STATE order by GROWTH) - GROWTH Growth_diff from (SELECT COMPANYID, STATE, GROWTH, max(GROWTH) OVER (PARTITION BY STATE) max_GROWTH FROM TOPCOMPANIES) order by 2,3 desc"'), httpheader=c(DB='jdbc:oracle:thin:@129.152.144.84:1521:ORCL', USER='C##cs329e_nh5797', PASS='orcl_nh5797', MODE='native_mode', MODEL='model', returnFor = 'R', returnDimensions = 'False'), verbose = TRUE), 1, 2^31-1))))

